apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  selector:
    name: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: {{cookiecutter.app_name}}
        image: $DOCKER_TAG
        env:
        - name: APPLICATION_ID
          value: "$APPLICATION_ID"

        # Pull the docker image every time before starting the pod.
        # Useful when debugging, but should be turned off in production.
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gce-ingress
spec:
  tls:
  - secretName: tls-secret
  # default backend in case requests don't match a path below
  backend:
    serviceName: backend
    servicePort: 8088
  rules:
  # default is *, replace the below with yours if restricting to a domain
  #- host: foo.bar.com
  #  http:
  - http:
      paths:
      - path: {{cookiecutter.endpoint}}
        backend:
          serviceName: backend
          servicePort: 8088
